# Generated by Django 4.2.1 on 2023-06-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_usuarios',
            new_name='id_usuario',
        ),
    ]
