# Generated by Django 4.2.1 on 2023-06-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_id_usuarios_usuarios_id_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
